server:
  port: 9090

#spring配置
spring:
  application:
    name: admin-manage
  datasource:
    url: jdbc:mysql://localhost:3306/cloudera?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
          initial-size: 3
          min-idle: 3
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statement: true
          max-pool-prepared-statement-per-connection-size: 20
          filters: stat,wall,log4j
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          use-global-datasource-stat: true
  #http配置
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8

#mybatis配置 2017.03.25
#mybatis:
 # type-aliases-package: com.finex.cloudera.entity
  #mapper-locations: com.finex.cloudera.web.mapper
  #config-location: classpath:mybatis-config.xml




logging:
   level: debug
   path: D:\var\




